# Generated by Django 3.2.6 on 2022-05-19 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academys', '0001_initial'),
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='completed_education',
            field=models.ManyToManyField(related_name='completed_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='education',
            name='job_posting',
            field=models.ManyToManyField(related_name='edu_posting', to='companys.JobPosting'),
        ),
        migrations.AddField(
            model_name='education',
            name='progressing_education',
            field=models.ManyToManyField(related_name='progressing_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academy',
            name='academy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
