# Generated by Django 3.2.6 on 2022-05-20 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academys', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='academy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academys.academy'),
            preserve_default=False,
        ),
    ]
