# Generated by Django 3.2.6 on 2022-05-19 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobseekers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tell', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('number_of_workers', models.IntegerField()),
                ('year_of_establishment', models.IntegerField()),
                ('industry', models.CharField(max_length=255)),
                ('company_size', models.CharField(max_length=255)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(max_length=255)),
                ('job_position', models.CharField(max_length=255)),
                ('welfare', models.TextField()),
                ('application_process', models.TextField()),
                ('registeration', models.DateTimeField()),
                ('expired', models.DateTimeField()),
                ('preferential_requirements', models.TextField()),
                ('requestments', models.TextField()),
                ('employment_type', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('application_jobseekers', models.ManyToManyField(related_name='application_postings', to='jobseekers.Jobseeker')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobpostings', to='companys.company')),
            ],
        ),
    ]
